### ISSUE TITLE
Particle JS header Broken

### ISSUE THREAD

**Issue by tomkiernan120** [tomkiernan120/Faze#19]
**Describe the bug**
Particle JS header broken, can see an error also in the web tools console.

**To Reproduce**
1. Go to 'https://tomkiernan120.github.io/Faze/' in a browser or if cloned, the /index.html

**Expected behavior**
Particles JS effect.

**Screenshots**
TODO

**Comment by tom-seegreen** [comment]
Looks as if this is fixed in commit https://github.com/tomkiernan120/Faze/commit/3c3e2020fc4426b70d5ab86a2aabf98f6e0785ff

**Comment by tomkiernan120** [comment]
Fixed in #21
